#!/usr/bin/env python

import argparse
import os

# Replace these values with your own information.
leaguefile = "union.lg"


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('--recover', dest='recover', action='store_true')
  parser.set_defaults(recover=False)
  args = parser.parse_args()

  host = "http://unionleaguebaseball.com/unionleague/file/"
  importfile = "ulb.lg.tar.gz"
  leaguepath = ("{0}/.Out of the Park Developments/OOTP Baseball 17/custdata/saved_games/" +
                "{1}").format(os.path.expanduser("~"), leaguefile)
  backuppath = "{0}.bk".format(leaguepath)

  if args.recover:
    if os.path.isdir(backuppath):
      os.system(
          "rm -rf '{0}' && mv '{1}' '{0}'".format(leaguepath, backuppath))
  else:
    if os.path.isdir(leaguepath):
      os.system(
          "rm -rf '{0}' && mv '{1}' '{0}'".format(backuppath, leaguepath))

    os.system("rm -rf '{0}' && mkdir '{0}'".format(leaguepath))
    os.chdir(leaguepath)

    os.system("wget {0}{1}".format(host, importfile))
    os.system("tar -xzf {0}".format(importfile))
    os.system("rm {0}".format(importfile))

    dirs = ["ballcaps", "jerseys", "news/html/images/league_logos",
            "news/html/images/team_logos", "settings"]
    for d in dirs:
      os.system("rm -rf '{0}' && cp -R '{1}' '{0}'".format(os.path.join(
          leaguepath, d), os.path.join(backuppath, d)))

if __name__ == "__main__":
  main()
